/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

import { AppTranslations, Language } from './types';

export const LANGUAGES: { code: Language; name: string; nativeName: string; dir: 'ltr' | 'rtl' }[] = [
  { code: 'en', name: 'English', nativeName: 'English', dir: 'ltr' },
  { code: 'ar', name: 'Arabic', nativeName: 'العربية', dir: 'rtl' },
  { code: 'es', name: 'Spanish', nativeName: 'Español', dir: 'ltr' },
  { code: 'pt', name: 'Portuguese', nativeName: 'Português', dir: 'ltr' },
];

export const TRANSLATIONS: Record<Language, AppTranslations> = {
  en: {
    nav: {
      home: 'Home',
      services: 'Services',
      howItWorks: 'How It Works',
      about: 'About',
      contact: 'Contact',
    },
    hero: {
      badge: 'GLOBAL AVIATION SUPPLY CHAIN',
      headingPrefix: 'Precision Sourcing for ',
      headingHighlight: 'Private Aircraft ',
      headingSuffix: 'in Orbit',
      description: 'The global gateway for sourcing, certifying, and moving high-performance engines, avionics, landing gear, and cabin structures between premium manufacturers, MROs, and elite operators.',
      ctaPrimary: 'Explore the Platform',
      ctaSecondary: 'Talk to our Team',
    },
    services: {
      eyebrow: 'WHAT MOVES THROUGH AIVUM',
      heading: 'Aviation Equipment Sourced & Transported Globally',
      items: [
        {
          id: 's1',
          title: 'Avionics & Flight Systems',
          desc: 'Ultra-precise cockpit avionics, auto-flight modules, navigation sensors, and communications suites.',
          iconName: 'sourcing',
        },
        {
          id: 's2',
          title: 'Turbofan Engines & Rotors',
          desc: 'High-thrust propulsion machinery, auxiliary power units (APU), and high-integrity rotor systems.',
          iconName: 'import',
        },
        {
          id: 's3',
          title: 'Landing Gear & Hydraulics',
          desc: 'Heavy-duty structural landing gear, advanced brake assemblies, and flight-control hydraulic lines.',
          iconName: 'maintenance',
        },
        {
          id: 's4',
          title: 'Custom Logistics & Customs',
          desc: 'Global regulatory compliance, fast customs clearing, and secure, high-value component escrow.',
          iconName: 'export',
        },
        {
          id: 's5',
          title: 'Cabin Systems & Overhaul',
          desc: 'Premium cabin electronics, structural refurbishment kits, and critical MRO shop-level parts.',
          iconName: 'logistics',
        },
      ],
    },
    process: {
      eyebrow: 'FLIGHT PATH TO DELIVERY',
      heading: 'Our Streamlined Supply Chain Lifecycle',
      steps: [
        {
          id: 1,
          number: '01',
          title: 'Parts Request',
          desc: 'Operators submit specifications, part numbers, and certification requirements to our secure registry.',
        },
        {
          id: 2,
          number: '02',
          title: 'Global Sourcing',
          desc: 'Our platform matches the request across certified suppliers, manufacturing partners, and MRO pools.',
        },
        {
          id: 3,
          number: '03',
          title: 'FAA / EASA Verification',
          desc: 'Every piece undergoes rigorous documentation checks and airworthiness certification review.',
        },
        {
          id: 4,
          number: '04',
          title: 'Secure Delivery',
          desc: 'Precision packaging and secure customs clearance deliver parts straight to your private hangar.',
        },
      ],
    },
    stats: {
      items: [
        { value: 12, suffix: '+', label: 'Years in Operation' },
        { value: 84, suffix: '', label: 'Countries Served' },
        { value: 14200, suffix: '+', label: 'Certified Parts Catalogued' },
        { value: 99.8, suffix: '%', label: 'On-Time Logistics Rate' },
      ],
    },
    about: {
      eyebrow: 'THE ORBIT OF TRUST',
      heading: 'Bridging Operators & Manufacturers Worldwide',
      paragraph1: 'Aivum was founded with a singular purpose: to eliminate friction from the global private aviation supply chain. Moving high-value, highly-regulated equipment across borders demands more than simple shipping—it requires absolute traceability, deep technical expertise, and an unwavering commitment to safety.',
      paragraph2: 'By treating critical aircraft components like orbiting satellites connected to a central data hub, we give MROs, operators, and global manufacturers a single, responsive gateway to keep executive fleets airborne with zero downtime.',
      tagline: 'Your mission critical is our standard orbit.',
    },
    contact: {
      eyebrow: 'ESTABLISH CONNECTIVITY',
      heading: 'Talk to an Aviation Expert',
      nameLabel: 'Your Full Name',
      emailLabel: 'Corporate Email Address',
      messageLabel: 'Sourcing Requirements or Message',
      submitButton: 'Transmit Inquiry',
      submittingState: 'Establishing Uplink...',
      successState: 'Inquiry Transmitted Successfully',
      phoneLabel: 'Global Operations Desk',
      emailContactLabel: 'Secured Communications',
      addressLabel: 'Aivum Orbital Hangar A-4, Geneva Int Airport',
    },
    footer: {
      tagline: 'Precision private aviation supply chain in constant orbit.',
      companyTitle: 'Company',
      servicesTitle: 'Services',
      legalTitle: 'Legal',
      links: {
        about: 'About Us',
        careers: 'Careers',
        press: 'Press Kit',
        privacy: 'Privacy Policy',
        terms: 'Terms of Service',
        cookies: 'Cookie Config',
      },
      copyright: '© 2026 Aivum S.A. All rights reserved. Sourced and delivered in orbital alignment.',
    },
  },
  ar: {
    nav: {
      home: 'الرئيسية',
      services: 'الخدمات',
      howItWorks: 'آلية العمل',
      about: 'من نحن',
      contact: 'اتصل بنا',
    },
    hero: {
      badge: 'سلسلة التوريد العالمية للطيران',
      headingPrefix: 'تأمين دقيق لـ ',
      headingHighlight: 'الطائرات الخاصة ',
      headingSuffix: 'في مدار دائم',
      description: 'البوابة العالمية لتأمين وتوثيق ونقل المحركات عالية الأداء، وأنظمة الملاحة الجوية، ومعدات الهبوط، وهياكل الكبائن بين نخبة المصنعين، ومراكز الصيانة، والمشغلين الدوليين.',
      ctaPrimary: 'استكشف المنصة',
      ctaSecondary: 'تحدث مع خبرائنا',
    },
    services: {
      eyebrow: 'ما يتحرك عبر إيفوم',
      heading: 'معدات طيران يتم تأمينها وشحنها عالمياً',
      items: [
        {
          id: 's1',
          title: 'أنظمة الطيران والملاحة الجوية',
          desc: 'أنظمة تحكم قمرة القيادة فائقة الدقة، ووحدات الطيران الآلي، وأجهزة استشعار الملاحة، وحزم الاتصالات الجوية.',
          iconName: 'sourcing',
        },
        {
          id: 's2',
          title: 'المحركات التوربينية والمراوح',
          desc: 'محركات دفع نفاثة عالية الأداء، ووحدات الطاقة المساعدة (APU)، وأنظمة الدوارات عالية المتانة.',
          iconName: 'import',
        },
        {
          id: 's3',
          title: 'معدات الهبوط والأنظمة الهيدروليكية',
          desc: 'هياكل معدات الهبوط للمهام الشاقة، ومجموعات الفرامل المتقدمة، وخطوط هيدروليك التحكم في الطيران.',
          iconName: 'maintenance',
        },
        {
          id: 's4',
          title: 'الخدمات اللوجستية المخصصة والجمارك',
          desc: 'الامتثال الكامل للوائح الدولية، والتخليص الجمركي السريع، وحسابات الضمان الآمنة للمكونات القيمة.',
          iconName: 'export',
        },
        {
          id: 's5',
          title: 'أنظمة الكبائن وأعمال الصيانة',
          desc: 'إلكترونيات الكبائن الفاخرة، وحزم التجديد الهيكلي، وقطع الغيار الحرجة المخصصة لورش الصيانة.',
          iconName: 'logistics',
        },
      ],
    },
    process: {
      eyebrow: 'مسار الرحلة للتسليم',
      heading: 'دورة حياة سلسلة التوريد المبسطة لدينا',
      steps: [
        {
          id: 1,
          number: '٠١',
          title: 'طلب قطع الغيار',
          desc: 'يقدم المشغلون المواصفات الفنية، وأرقام القطع، ومتطلبات الاعتماد إلى سجلنا الآمن.',
        },
        {
          id: 2,
          number: '٠٢',
          title: 'البحث والتأمين العالمي',
          desc: 'تقوم منصتنا بمطابقة الطلب عبر الموردين المعتمدين، وشركاء التصنيع، وشبكات الصيانة والإصلاح.',
        },
        {
          id: 3,
          number: '٠٣',
          title: 'التحقق والتوثيق المعتمد',
          desc: 'تخضع كل قطعة لفحوصات وثائقية صارمة ومراجعة شهادات الصلاحية للطيران (FAA / EASA).',
        },
        {
          id: 4,
          number: '٠٤',
          title: 'التسليم الآمن',
          desc: 'تغليف دقيق وتخليص جمركي آمن يسلم قطع الغيار مباشرة إلى حظيرة الطائرات الخاصة بك.',
        },
      ],
    },
    stats: {
      items: [
        { value: 12, suffix: '+', label: 'عاماً من العمليات' },
        { value: 84, suffix: '', label: 'دولة يتم خدمتها' },
        { value: 14200, suffix: '+', label: 'قطعة غيار معتمدة مسجلة' },
        { value: 99.8, suffix: '%', label: 'معدل دقة الخدمات اللوجستية' },
      ],
    },
    about: {
      eyebrow: 'مدار الثقة',
      heading: 'جسر يربط المشغلين والمصنعين حول العالم',
      paragraph1: 'تأسست إيفوم لغرض واحد: إزالة العقبات من سلسلة توريد الطيران الخاص العالمية. إن نقل المعدات عالية القيمة والخاضعة للوائح صارمة عبر الحدود يتطلب ما هو أكثر من مجرد الشحن العادي؛ إنه يتطلب تتبعاً مطلقاً، وخبرة فنية عميقة، والتزاماً صارماً بالسلامة الجوية.',
      paragraph2: 'من خلال معاملة مكونات الطائرات الحيوية كأقمار صناعية تدور حول مركز بيانات موحد، فإننا نمنح مراكز الصيانة والمشغلين والمصنعين بوابات استجابة سريعة لضمان بقاء الأساطيل الفاخرة محلقة دون أي توقف.',
      tagline: 'مهمتكم الحرجة هي مدار عملنا اليومي.',
    },
    contact: {
      eyebrow: 'إنشاء اتصال',
      heading: 'تحدث مع خبير طيران',
      nameLabel: 'الاسم بالكامل',
      emailLabel: 'البريد الإلكتروني للشركة',
      messageLabel: 'متطلبات التوريد أو نص الرسالة',
      submitButton: 'إرسال الاستفسار',
      submittingState: 'جاري إنشاء الاتصال اللاسلكي...',
      successState: 'تم إرسال الاستفسار بنجاح',
      phoneLabel: 'مكتب العمليات العالمي',
      emailContactLabel: 'الاتصالات المشفرة الآمنة',
      addressLabel: 'حظيرة إيفوم المدارية A-4، مطار جنيف الدولي',
    },
    footer: {
      tagline: 'سلسلة توريد طيران خاص دقيقة في مدار مستمر.',
      companyTitle: 'الشركة',
      servicesTitle: 'الخدمات',
      legalTitle: 'قانوني',
      links: {
        about: 'من نحن',
        careers: 'وظائف',
        press: 'الصحافة',
        privacy: 'سياسة الخصوصية',
        terms: 'شروط الخدمة',
        cookies: 'إعدادات الكوكيز',
      },
      copyright: '© ٢٠٢٦ إيفوم (Aivum S.A). جميع الحقوق محفوظة. تم تأمينه وشحنه بمحاذاة مدارية.',
    },
  },
  es: {
    nav: {
      home: 'Inicio',
      services: 'Servicios',
      howItWorks: 'Cómo funciona',
      about: 'Nosotros',
      contact: 'Contacto',
    },
    hero: {
      badge: 'CADENA DE SUMINISTRO GLOBAL DE AVIACIÓN',
      headingPrefix: 'Abastecimiento de precisión para ',
      headingHighlight: 'Aeronaves Privadas ',
      headingSuffix: 'en Órbita',
      description: 'El portal global para abastecer, certificar y transportar motores de alto rendimiento, aviónica, trenes de aterrizaje y estructuras de cabina entre fabricantes premium, centros MRO y operadores de élite.',
      ctaPrimary: 'Explorar la Plataforma',
      ctaSecondary: 'Hablar con el Equipo',
    },
    services: {
      eyebrow: 'LO QUE SE MUEVE A TRAVÉS DE AIVUM',
      heading: 'Equipos de Aviación Suministrados y Transportados Globalmente',
      items: [
        {
          id: 's1',
          title: 'Aviónica y Sistemas de Vuelo',
          desc: 'Aviónica de cabina de ultraprecisión, módulos de vuelo automático, sensores de navegación y suites de comunicación.',
          iconName: 'sourcing',
        },
        {
          id: 's2',
          title: 'Motores Turbofán y Rotores',
          desc: 'Maquinaria de propulsión de alto empuje, unidades de potencia auxiliar (APU) y sistemas de rotor de alta integridad.',
          iconName: 'import',
        },
        {
          id: 's3',
          title: 'Trenes de Aterrizaje e Hidráulica',
          desc: 'Trenes de aterrizaje estructurales pesados, conjuntos de frenos avanzados y líneas hidráulicas de control de vuelo.',
          iconName: 'maintenance',
        },
        {
          id: 's4',
          title: 'Logística Personalizada y Aduanas',
          desc: 'Cumplimiento normativo global, despacho de aduanas rápido y depósito en garantía seguro de componentes de alto valor.',
          iconName: 'export',
        },
        {
          id: 's5',
          title: 'Sistemas de Cabina y Overhaul',
          desc: 'Electrónica premium de cabina, kits de reacondicionamiento estructural y piezas críticas de nivel de taller MRO.',
          iconName: 'logistics',
        },
      ],
    },
    process: {
      eyebrow: 'RUTA DE VUELO HACIA LA ENTREGA',
      heading: 'Nuestro Ciclo de Vida Simplificado de la Cadena de Suministro',
      steps: [
        {
          id: 1,
          number: '01',
          title: 'Solicitud de Piezas',
          desc: 'Los operadores envían especificaciones, números de pieza y requisitos de certificación a nuestro registro seguro.',
        },
        {
          id: 2,
          number: '02',
          title: 'Abastecimiento Global',
          desc: 'Nuestra plataforma compara la solicitud entre proveedores certificados, socios fabricantes y reservas MRO.',
        },
        {
          id: 3,
          number: '03',
          title: 'Verificación FAA / EASA',
          desc: 'Cada componente se somete a rigurosas comprobaciones de documentación y revisión de certificación de aeronavegabilidad.',
        },
        {
          id: 4,
          number: '04',
          title: 'Entrega Asegurada',
          desc: 'Embalaje de precisión y despacho de aduanas seguro entregan las piezas directamente a su hangar privado.',
        },
      ],
    },
    stats: {
      items: [
        { value: 12, suffix: '+', label: 'Años en Operación' },
        { value: 84, suffix: '', label: 'Países Atendidos' },
        { value: 14200, suffix: '+', label: 'Piezas Certificadas Catalogadas' },
        { value: 99.8, suffix: '%', label: 'Tasa de Logística a Tiempo' },
      ],
    },
    about: {
      eyebrow: 'LA ÓRBITA DE LA CONFIANZA',
      heading: 'Conectando Operadores y Fabricantes a Nivel Mundial',
      paragraph1: 'Aivum fue fundada con un propósito singular: eliminar la fricción de la cadena de suministro de la aviación privada global. Mover equipos de alto valor y altamente regulados a través de las fronteras exige más que un envío simple: requiere trazabilidad absoluta, experiencia técnica profunda y un compromiso inquebrantable con la seguridad.',
      paragraph2: 'Al tratar los componentes críticos del avión como satélites en órbita conectados a un centro de datos unificado, brindamos a los centros MRO, operadores y fabricantes globales un portal de respuesta rápida para mantener las flotas ejecutivas en el aire con cero inactividad.',
      tagline: 'Su misión crítica es nuestra órbita estándar.',
    },
    contact: {
      eyebrow: 'ESTABLECER CONECTIVIDAD',
      heading: 'Hable con un Experto en Aviación',
      nameLabel: 'Nombre Completo',
      emailLabel: 'Dirección de Correo Corporativo',
      messageLabel: 'Requisitos de Abastecimiento o Mensaje',
      submitButton: 'Transmitir Consulta',
      submittingState: 'Estableciendo Enlace...',
      successState: 'Consulta Transmitida con Éxito',
      phoneLabel: 'Mesa de Operaciones Globales',
      emailContactLabel: 'Comunicaciones Aseguradas',
      addressLabel: 'Hangar Orbital A-4 de Aivum, Aeropuerto Int de Ginebra',
    },
    footer: {
      tagline: 'Cadena de suministro de aviación privada de precisión en órbita constante.',
      companyTitle: 'Compañía',
      servicesTitle: 'Servicios',
      legalTitle: 'Legal',
      links: {
        about: 'Sobre Nosotros',
        careers: 'Carreras',
        press: 'Sala de Prensa',
        privacy: 'Política de Privacidad',
        terms: 'Términos de Servicio',
        cookies: 'Configuración de Cookies',
      },
      copyright: '© 2026 Aivum S.A. Todos los derechos reservados. Abastecido y entregado en alineación orbital.',
    },
  },
  pt: {
    nav: {
      home: 'Início',
      services: 'Serviços',
      howItWorks: 'Como funciona',
      about: 'Sobre nós',
      contact: 'Contato',
    },
    hero: {
      badge: 'CADEIA DE SUPRIMENTOS GLOBAL DE AVIAÇÃO',
      headingPrefix: 'Fornecimento de precisão para ',
      headingHighlight: 'Aeronaves Privadas ',
      headingSuffix: 'em Órbita',
      description: 'O portal global para fornecimento, certificação e transporte de motores de alta performance, aviônicos, trens de pouso e estruturas de cabine entre fabricantes premium, centros MRO e operadores de elite.',
      ctaPrimary: 'Explorar a Plataforma',
      ctaSecondary: 'Falar com a Equipe',
    },
    services: {
      eyebrow: 'O QUE SE MOVE ATRAVÉS DA AIVUM',
      heading: 'Equipamentos de Aviação Sourced & Transportados Globalmente',
      items: [
        {
          id: 's1',
          title: 'Aviônicos e Sistemas de Voo',
          desc: 'Aviônicos de cockpit de ultraprecisão, módulos de voo automático, sensores de navegação e pacotes de comunicação.',
          iconName: 'sourcing',
        },
        {
          id: 's2',
          title: 'Turbofans e Rotores',
          desc: 'Maquinaria de propulsão de alto empuxo, unidades de energia auxiliar (APU) e sistemas de rotor de alta integridade.',
          iconName: 'import',
        },
        {
          id: 's3',
          title: 'Trens de Pouso e Hidráulica',
          desc: 'Trens de pouso estruturais pesados, conjuntos de freios avançados e linhas hidráulicas de controle de voo.',
          iconName: 'maintenance',
        },
        {
          id: 's4',
          title: 'Logística Customizada e Alfândega',
          desc: 'Conformidade regulatória global, desembaraço aduaneiro rápido e custódia segura de componentes de alto valor.',
          iconName: 'export',
        },
        {
          id: 's5',
          title: 'Sistemas de Cabine e Overhaul',
          desc: 'Eletrônicos de cabine premium, kits de reforma estrutural e peças críticas de nível de oficina MRO.',
          iconName: 'logistics',
        },
      ],
    },
    process: {
      eyebrow: 'ROTA DE VOO ATÉ A ENTREGA',
      heading: 'Nosso Ciclo de Vida Simplificado da Cadeia de Suprimentos',
      steps: [
        {
          id: 1,
          number: '01',
          title: 'Solicitação de Peças',
          desc: 'Os operadores enviam especificações, códigos de peça e requisitos de certificação ao nosso registro seguro.',
        },
        {
          id: 2,
          number: '02',
          title: 'Fornecimento Global',
          desc: 'Nossa plataforma combina a solicitação entre fornecedores certificados, parceiros fabricantes e reservas MRO.',
        },
        {
          id: 3,
          number: '03',
          title: 'Verificação FAA / EASA',
          desc: 'Cada componente passa por rigorosas verificações de documentação e revisão de certificação de aeronavegabilidade.',
        },
        {
          id: 4,
          number: '04',
          title: 'Entrega Segura',
          desc: 'Embalagem de precisão e desembaraço aduaneiro seguro entregam as peças diretamente ao seu hangar privado.',
        },
      ],
    },
    stats: {
      items: [
        { value: 12, suffix: '+', label: 'Anos em Operação' },
        { value: 84, suffix: '', label: 'Países Atendidos' },
        { value: 14200, suffix: '+', label: 'Peças Certificadas Catalogadas' },
        { value: 99.8, suffix: '%', label: 'Taxa de Logística no Prazo' },
      ],
    },
    about: {
      eyebrow: 'A ÓRBITA DA CONFIANÇA',
      heading: 'Conectando Operadores e Fabricantes Globalmente',
      paragraph1: 'A Aivum foi fundada com um propósito único: eliminar o atrito da cadeia de suprimentos da aviação privada global. Mover equipamentos de alto valor e altamente regulamentados através das fronteiras exige mais do que um simples frete — exige rastreabilidade absoluta, profunda experiência técnica e um compromisso inabalável com a segurança.',
      paragraph2: 'Ao tratar componentes críticos de aeronaves como satélites em órbita conectados a um centro de dados unificado, oferecemos a oficinas MRO, operadores e fabricantes globais um portal de resposta rápida para manter frotas executivas voando sem tempo de inatividade.',
      tagline: 'Sua missão crítica é nossa órbita padrão.',
    },
    contact: {
      eyebrow: 'ESTABELECER CONECTIVIDADE',
      heading: 'Fale com um Especialista em Aviação',
      nameLabel: 'Nome Completo',
      emailLabel: 'Endereço de E-mail Corporativo',
      messageLabel: 'Requisitos de Fornecimento ou Mensagem',
      submitButton: 'Transmitir Consulta',
      submittingState: 'Estabelecendo Conexão...',
      successState: 'Consulta Transmitida com Sucesso',
      phoneLabel: 'Mesa de Operações Globais',
      emailContactLabel: 'Comunicação Segura',
      addressLabel: 'Hangar Orbital A-4 da Aivum, Aeroporto Int de Genebra',
    },
    footer: {
      tagline: 'Cadeia de suprimentos de precisão para aviação privada em órbita constante.',
      companyTitle: 'Empresa',
      servicesTitle: 'Serviços',
      legalTitle: 'Legal',
      links: {
        about: 'Sobre Nós',
        careers: 'Carreiras',
        press: 'Sala de Imprensa',
        privacy: 'Política de Privacidade',
        terms: 'Termos de Serviço',
        cookies: 'Configuração de Cookies',
      },
      copyright: '© 2026 Aivum S.A. Todos os direitos reservados. Fornecido e entregue em alinhamento orbital.',
    },
  },
};
